'use client'

import { convertImageFileToBase64 } from '@/lib/utils'
import { useCallback, useState } from 'react'
import { useAccount } from 'wagmi'
import { APIService } from '../api-service'
import { ChatMessage, ChatState } from '../types'

const INITIAL_MESSAGES: ChatMessage[] = [
  {
    type: 'output',
    content: 'Initializing Seraph Neural Interface...',
    timestamp: Date.now(),
  },
  {
    type: 'output',
    content: 'Connected to Virtuals Protocol.',
    timestamp: Date.now() + 1,
  },
  {
    type: 'output',
    content: 'Ready for interaction. Type a message to begin.',
    timestamp: Date.now() + 2,
  },
  {
    type: 'output',
    content: 'Run "detect-image {image_uri}" to analyze an image.',
    timestamp: Date.now() + 3,
  },
  {
    type: 'output',
    content: 'Or upload an image using the button.',
    timestamp: Date.now() + 4,
  },
]

export function useChat() {
  const [state, setState] = useState<ChatState>({
    messages: INITIAL_MESSAGES,
    isLoading: false,
    error: null,
  })

  const { address } = useAccount()

  const sendMessage = useCallback(
    async (message: string) => {
      if (!message.trim()) return

      setState((prev) => ({
        ...prev,
        messages: [
          ...prev.messages,
          {
            type: 'input',
            content: message,
            timestamp: Date.now(),
          },
        ],
        isLoading: true,
        error: null,
      }))

      try {
        const response = await APIService.sendMessage(address, message)
        const cleanedResponse = response.replace(/(?:undefined: )+/g, '')

        setState((prev) => ({
          ...prev,
          messages: [
            ...prev.messages,
            {
              type: 'output',
              content: cleanedResponse,
              timestamp: Date.now(),
            },
          ],
          isLoading: false,
        }))
      } catch (error) {
        console.error('Chat error:', error)
        const errorMessage =
          error instanceof Error
            ? error.message
            : 'An unexpected error occurred'

        setState((prev) => ({
          ...prev,
          messages: [
            ...prev.messages,
            {
              type: 'output',
              content: `Error: ${errorMessage}. Please try again.`,
              timestamp: Date.now(),
            },
          ],
          isLoading: false,
          error: errorMessage,
        }))
      }
    },
    [address]
  )

  const sendImage = useCallback(
    async (file: File) => {
      if (!file) return

      setState((prev) => ({
        ...prev,
        messages: [
          ...prev.messages,
          {
            type: 'input',
            content: `detect-image ${file.name}`,
            timestamp: Date.now(),
          },
        ],
        isLoading: true,
        error: null,
      }))

      try {
        const base64Image = await convertImageFileToBase64(file)
        const response = await APIService.detectImage(base64Image)

        const responseString = `Alright, here's what I found for the image "${
          file.name
        }":

        - AI Detection: Nope, this doesn't seem to be generated by AI.
        - Confidence in this result? I'd say about ${response.confidence.toFixed(
          4
        )}.
        - Similarity to known patterns: ${response.similarity.toFixed(4)}.
        
        Here's the top 5 miners prediction scores:
        1. ${response.predictions[0].toFixed(4)}
        2. ${response.predictions[1].toFixed(4)}
        3. ${response.predictions[2].toFixed(4)}
        4. ${response.predictions[3].toFixed(4)}
        5. ${response.predictions[4].toFixed(4)}
        
        Processed by node: ${response.fqdn}.`

        setState((prev) => ({
          ...prev,
          messages: [
            ...prev.messages,
            {
              type: 'output',
              content: responseString,
              timestamp: Date.now(),
            },
          ],
          isLoading: false,
        }))
      } catch (error) {
        console.error('Image upload error:', error)
        const errorMessage =
          error instanceof Error
            ? error.message
            : 'An unexpected error occurred'

        setState((prev) => ({
          ...prev,
          messages: [
            ...prev.messages,
            {
              type: 'output',
              content: `Error: ${errorMessage}. Please try again.`,
              timestamp: Date.now(),
            },
          ],
          isLoading: false,
          error: errorMessage,
        }))
      }
    },
    [address]
  )

  return {
    messages: state.messages,
    isLoading: state.isLoading,
    error: state.error,
    sendMessage,
    sendImage,
  }
}
